[main]
# 폰트 설정
font=JetBrainsMono Nerd Font:size=12
# 글자 간격 조정
letter-spacing=0
# 여백 설정
pad=15x15 # 가로x세로 여백

[colors-dark]
# 배경 투명도 (0.0 ~ 1.0)
alpha=0.9
# Catppuccin Mocha 느낌
foreground=cdd6f4
background=1e1e2e

## Normal colors
regular0=45475a # black
regular1=f38ba8 # red
regular2=a6e3a1 # green
regular3=f9e2af # yellow
regular4=89b4fa # blue
regular5=f5c2e7 # magenta
regular6=94e2d5 # cyan
regular7=bac2de # white

